-- Generated by nwg-displays on 2026-06-11 at 21:01:22. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1200@60.0",
    position = "3840x0",
    scale = 1.5
})
hl.monitor({
    output = "DP-3",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.5000000000000004
})
