language = "en-US"
region = "pt-BR"

[modules]
left = [ [ "Workspaces", "Status", "MediaPlayer" ] ]
center = [ "Tempo" ]
right = [ "notifications", "calendar", "clock", "SystemInfo", [  "Tray", "Privacy", "Settings" ] ]

[updates]
check_cmd = "checkupdates; paru -Qua"
update_cmd = 'ghostty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true

[media_player]
max_title_length = 50

[settings]
shutdown_cmd = "shutdown now"
suspend_cmd = "hyprlock & sleep 1 && systemctl suspend"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"
bluetooth_more_cmd = "blueman-manager"

[[CustomModule]]
name = "calendar"
icon = ""
command = "gnome-calendar"

[[CustomModule]]
name = "clock"
icon = "󱑆"
command = "gnome-clocks"

[[CustomModule]]
name = "notifications"
icon = "󰂚"
command = "~/.config/hypr/scripts/ashell-mako.sh toggle"
listen_cmd = "~/.config/hypr/scripts/ashell-mako.sh listen"
icons.'dnd' = "󰂛"
alert = ".*dnd.*"
